services:
  logisearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msbrossai-logisearch
    ports:
      - "5175:80"
    env_file:
      - ../../.env.local
    networks:
      - msbrossai-network
    restart: unless-stopped

networks:
  msbrossai-network:
    driver: bridge
